kind: Pod
apiVersion: v1
metadata:
  name: some-pod-with-secret
spec:
  restartPolicy: Never
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  containers:
  - name: some-pod-with-secret
    image: alpine
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/root/.kube/"


