kind: Pod
apiVersion: v1
metadata:
  name: some-pod
spec:
  restartPolicy: Never  
  containers:
    - name: some-pod
      image: alpine
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
