---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-pod-config
data:
  sleep-interval: "3"
---
kind: Pod
apiVersion: v1
metadata:
  name: some-pod
spec:
  restartPolicy: Never  
  containers:
    - name: some-pod
      image: alpine
      command: ["/bin/sh", "-ec", "while :; do echo $INTERVAL'.'; sleep $INTERVAL ; done"]
      livenessProbe:
        exec:
          command:
          - ls
      readinessProbe:
        exec:
          command:
          - ls
      env:
      - name: INTERVAL
        valueFrom:
          configMapKeyRef:
            name: some-pod-config
            key: sleep-interval
