apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "*/2 * * * *"  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: some-pod
            image: alpine
            command: ["/bin/sh", "-ec", "for i in `seq 1 100`; do echo $i; sleep 1 ; done"]
