---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        version: v-2
    spec:
      containers:
      - name: my-app
        image: inanme/app:2
        imagePullPolicy: Always
        args: ["8081"]
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /status
            port: 8081
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - name: mport
    protocol: TCP
    port: 8081
    #nodePort: 8080
  type: LoadBalancer
