---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        version: v-%version%
    spec:
      containers:
      - name: my-app
        image: inanme/app:%version%
        imagePullPolicy: Always
        args: ["%port%"]
        ports:
        - containerPort: %port%
        livenessProbe:
          httpGet:
            path: /status
            port: %port%
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: %port%
          initialDelaySeconds: 5
        env:
        - name: APP_VERSION
          value: "%version%"  
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - name: mport
    protocol: TCP
    port: %port%
    #nodePort: 8080
  type: LoadBalancer
