kind: Pod
apiVersion: v1
metadata:
  name: some-pod-pvc3
spec:
  restartPolicy: Never  
  containers:
    - name: some-pod
      image: alpine
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      livenessProbe:
        exec:
          command:
          - ls
      readinessProbe:
        exec:
          command:
          - ls
      volumeMounts:
      - name: pvc
        mountPath: /data/db       
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc0002
