kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001
  labels:
    name: pv0001
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001"
